# Generated by Django 4.0.5 on 2022-07-14 07:26

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='republish',
            field=models.BooleanField(default=True, verbose_name='Переиздание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN', 'В работе'), ('RD', 'Исполнено'), ('NT', 'Уведомить о поступлении'), ('CAN', 'Отменено')], default='in_progress', max_length=20, verbose_name='Статус заказа')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.TextField(blank=True, help_text='Комментарий к заказу', verbose_name='Комментарий к заказу')),
                ('buyer_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('buyer_surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1}-\\d{3}-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='books.book')),
            ],
        ),
    ]
