# Generated by Django 4.0.5 on 2022-07-11 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN', 'В работе'), ('RD', 'Исполнено'), ('NT', 'Уведомить о поступлении'), ('CAN', 'Отменено')], default='in_progress', max_length=20, verbose_name='Статус заказа')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.TextField(blank=True, help_text='Комментарий к заказу', verbose_name='Комментарий к заказу')),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='books.book')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
        ),
    ]
