# Generated by Django 4.0.5 on 2022-07-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='republish',
            field=models.BooleanField(default=True, verbose_name='Переиздание'),
        ),
    ]
