# Generated by Django 4.0.5 on 2022-07-14 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_republish_alter_book_description_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_city',
            field=models.CharField(default=1, max_length=100, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{1}-\\d{3}-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN', 'В работе'), ('RD', 'Исполнено'), ('NT', 'Уведомить о поступлении'), ('CAN', 'Отменено')], default='IN', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
